enable_remote:
  type: bool
  default: true

remote_base_url:
  type: string
  default: "https://papers.eliteskillset.com"

blocks:
  type: objects
  default: []
  schema:
    name: block
    identifier: name
    properties:
      name:
        type: string
        required: true
        validations:
          min_length: 1
      topic_ids:
        type: string
      all_topics:
        type: boolean
      category_ids:
        type: categories
      exclude_topic_ids:
        type: string
      position:
        type: enum
        default: bottom
        choices:
          - bottom
          - top
      html:
        type: string
        required: true
      locale_overrides:
        type: objects
        schema:
          name: locale_override
          identifier: locale
          properties:
            locale:
              type: string
            html:
              type: string
